### ISSUE TITLE
Problem with uploaded tasks

### ISSUE THREAD

**Issue by hermes3por3** [corinis/synckolab#1]
Tasks get uploaded to server with wrong dates: NaN-NaN-NaNTNaN:NaN:NaN

**Comment by corinis** [comment]
Can you provide a little more information: Synckolab version, tbird version, which format you use?

**Comment by hermes3por3** [comment]
I am using Daily 36.0a1 32b in Windows 8.1 x64 (also in EarlyBird 35.0a2 Kubuntu 14.01 x64), latest Synckolab from git source. Didn't try in stableThunderbird.

**Comment by corinis** [comment]
it might be that there was a change in data structure for more recent tbird/lightning rleases... I will see if I can reproduce this.

**Comment by hermes3por3** [comment]
It might be something with the date primitive, though I'm not sure.

**Comment by adamreichold** [comment]
I think I encounter the same problem using Thunderbird 38.0.1, Lightning 4.0.0.1 and SyncKolab 3.1.6 configured for the XML/Kolab3 format. (I also tried the latest nightly from gargan.org but it is labelled as 3.1.4 and does show the same issues.)

From the console, I see the following types of error message:
- `CONVERTING: 15/NaN - 7200 - undefined vs. Invalid Date`
- `TypeError: tmp_date.getTime is not a function` at line 526 of file `chrome://synckolab/content/calendarTools.js`
- The created message bodies contain lines like

```
Start date: NaN-NaN-NaNTNaN:NaN:NaN
End date: NaN-NaN-NaNTNaN:NaN:NaN
```

whereas the attachments contains data like

```
<dtstamp><date-time>NaN-NaN-NaNTNaN:NaN:NaN</date-time></dtstamp>
```

I would be glad to provide any further assistance with reproducing this.

**Comment by corinis** [comment]
this is fixed now, please try the current nightly. If it works I will upload it to amo asap

**Comment by adamreichold** [comment]
Hello again,

thank you for looking into this! I just tried the nightly build (externally still calls itself 3.4, but the settings dialog shows 3.7) and sadly it still does not work, albeit with a different error message.

Trying to synchronize a calender fails with

```
Timestamp: 11.10.2015 09:59:16
Error: ReferenceError: assignment to undeclared variable calDateTime
Source: chrome://synckolab/content/calendarTools.js
Line: 542 
```

with SyncKolab freezing afterwards. Trying to synchronize tasks fails with

```
Timestamp: 11.10.2015 10:02:51
Error: Beim Schreiben in den Kalender Home ist ein Fehler aufgetreten! Fehlercode: MODIFICATION_FAILED. Beschreibung:
Source: resource://calendar/modules/calUtils.jsm -> file:///home/user/.thunderbird/6ul21rc7.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Line: 963
```

but the add-on continues to work and displays the error message.

Do you want to continue to track this here or should I open a separate issue?

**Comment by corinis** [comment]
no its fine... this error should be fixed as well.  (try the new nightly)

**Comment by adamreichold** [comment]
Hello again,

I tried the latest nightly and synchronizing tasks still fails with the same error message whereas synchronizing a calendar now fails with

```
Timestamp: 11.10.2015 12:28:38
Error: NS_ERROR_OBJECT_IS_IMMUTABLE: Component returned failure code: 0x80460002 (NS_ERROR_OBJECT_IS_IMMUTABLE) [calIDateTime.year]
Source: chrome://synckolab/content/tools/text.js
Line: 357
```

**Comment by corinis** [comment]
Date handling is a pain... I hope this works now. please check out the new nightly

**Comment by adamreichold** [comment]
Hello again,

thank you for keeping up with this. The synchronization of calender now runs through, but doing it again immediately yields a message that both the local and the remote version changed.

If I choose Cancel then to update the remote version, it runs through. However, if I choose Ok to update the local version, it fails with

```
Timestamp: 11.10.2015 14:14:27
Error: TypeError: tmp_date is undefined
Source: chrome://synckolab/content/calendarTools.js
Line: 920
```

Also synchronization of tasks does seem to update the entries on the server, it stills fails with

```
Timestamp: 11.10.2015 14:18:05
Error: Beim Schreiben in den Kalender Home ist ein Fehler aufgetreten! Fehlercode: MODIFICATION_FAILED. Beschreibung: 
Source: resource://calendar/modules/calUtils.jsm -> file:///home/user/.thunderbird/6ul21rc7.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Line: 963
```

in the end.

**Comment by corinis** [comment]
Sorry that we have to do that so incrementally (unfortunately I dont have a use case setup right now that handles that path) - but I think I got all jsDate references (was the issue in that case again) cleaned out now.
annoying api changes...
ps.: new nightly is built

**Comment by adamreichold** [comment]
Hello again,

the latest nightly runs through synchronizing the calendar with both selections and does not crash due to date handling.

What is not working is synchronizing tasks which fails with the above error message. Also each calendar synchronization reports that both local and remote versions did change even though neither actually did change.

**Comment by corinis** [comment]
hi...
I am not sure how to reproduce the problem.... because its actually in a lightning library and not synckolab code directly (which might still be the original problem... but right now I cannot reproduce it).

as for the "both changed": There are a few things that might fix/help me solve the issue:
- check the console in debug mode and see on which "field" the equals check fails (it should print x NOT EQUALS yy). If it is a field that did not change (mabye its again date related), best send me the problematic entry (send me the *.eml file - since that contains sensitive information like email addresses mail it directly to skbugs(at)corinis,net instead of attaching it). 
- delete all entries from the server (i.e. rename the imap folder and create a new one with the old name). Now when syncing all entries should be re-created. this might fix the issue (if its server parsing related)

**Comment by adamreichold** [comment]
Hello again,

I enabled debug logging and here is what I guess is the relevant part of the output which indeed does seem to indicate a date-related problem:

```
parsing message... 
1 - parsed event (message2Event) 
({synckolab:"3.1.7", type:"calendar", uid:"972ba0c1-4698-493c-b68b-e3c77196815d", creationDate:"2015-10-12T16:00:00", lastModified:"2015-10-12T16:00:00", sensitivity:"public", startDate:{tz:"Europe/Berlin", allday:false, dateTime:"2015-10-12T16:00:00"}, endDate:{tz:"Europe/Berlin", allday:false, dateTime:"2015-10-12T17:00:00"}, title:"foobar", location:"barfoo", showTimeAs:"busy"})
1 - Event To JSON
1 - CONVERTING -001/12/31 00:00:00 Europe/Berlin isDate=0 nativeTime=-62167219200000000: 0/23 - 0 - undefined vs. Fri Dec 31 -0001 00:00:00 GMT+0100 (LMT)
CONVERTING -001/12/31 00:00:00 Europe/Berlin isDate=0 nativeTime=-62167219200000000: 0/23 - 0 - undefined vs. Fri Dec 31 -0001 00:00:00 GMT+0100 (LMT)
1 - CONVERTING -001/12/31 00:00:00 Europe/Berlin isDate=0 nativeTime=-62167219200000000: 0/23 - 0 - undefined vs. Fri Dec 31 -0001 00:00:00 GMT+0100 (LMT)
1 - CONVERTING -001/12/31 00:00:00 Europe/Berlin isDate=0 nativeTime=-62167219200000000: 0/23 - 0 - undefined vs. Fri Dec 31 -0001 00:00:00 GMT+0100 (LMT)
1 - findevent returned :972ba0c1-4698-493c-b68b-e3c77196815d(972ba0c1-4698-493c-b68b-e3c77196815d) for 972ba0c1-4698-493c-b68b-e3c77196815d caching 22 events
syncDbFile:  (Account/calendar_Home/972ba0c1_4698_493c_b68b_e3c77196815d)
idxEntry:[xpconnect wrapped nsIFile]
Event exists local: 972ba0c1-4698-493c-b68b-e3c77196815d
1 - not equals: lastModified a: 2015-10-12T16:00:00 b: undefined
In parse Message cEvent DOES NOT EQUALS foundEvent
2 - not equals: creationDate a: undefined b: 2015-10-12T16:00:00
In parse Message cEvent DOES NOT equal newEvent
not equals (strlen): dateTime a: -1-12-31T00:00:0017 b: 2015-10-12T16:00:0019
not equals: startDate a: [object Object] b: [object Object]
In parse Message foundEvent DOES NOT equal newEvent
Changed on server and local: 972ba0c1-4698-493c-b68b-e3c77196815d
```

**Comment by corinis** [comment]
Just created another build - the creationDate and lastModified where typos - they shouldnt be included in the "equals" method. The startDate is more interesting.. there seems to be some kind of issue. Maybe try cleaning out the the entries in the imap folder (as described above). It might be that some data is corrupted.

**Comment by adamreichold** [comment]
Hello again,

using the last build, I can now synchronize calender items and tasks. Thank you!

One thing I noticed when doing is that completed items always seem to be detected as locally modified since the server-side storage of the completion information seems broken, c.f.

```
1 - parsed event (message2Event) 
({synckolab:"3.1.7", type:"task", completed:null, uid:"1fd1f786-b482-47e8-a1dc-fb9f3a0cb3ad", sensitivity:"public", title:"foobar", priority:"1", status:"completed", showTimeAs:"busy"})
1 - Event To JSON
2 - findevent returned :1fd1f786-b482-47e8-a1dc-fb9f3a0cb3ad(1fd1f786-b482-47e8-a1dc-fb9f3a0cb3ad) for 1fd1f786-b482-47e8-a1dc-fb9f3a0cb3ad caching 6 events
syncDbFile:  (Host_Europe/task_Home/1fd1f786_b482_47e8_a1dc_fb9f3a0cb3ad)
idxEntry:[xpconnect wrapped nsIFile]
Event exists local: 1fd1f786-b482-47e8-a1dc-fb9f3a0cb3ad
1 - not equals: completed a: not found b: 100
In parse Message cEvent DOES NOT EQUALS foundEvent
 In parse Message cEvent equals newEvent
not equals (strlen): completed a: 1003 b: null4
In parse Message foundEvent DOES NOT equal newEvent
client changed 1fd1f786-b482-47e8-a1dc-fb9f3a0cb3ad - undefined
4 - updating [undefined]
```

(The log was produced using an empty IMAP folder and the behaviour does not change when repeating the synchronization.)

**Comment by corinis** [comment]
There was a typo and I also added some extra logic for tasks - this should fix the issue you described. If you can please test out if it works.

If it does not work, it would make more sense to open a new issue now (since the sync completes we can close this oneforgood :) )

**Comment by adamreichold** [comment]
Hello again,

I agree that handling of the completion information should be a separate bug since it does not seem to be related to date handling. However, using the latest nightly (201510111935), the add-on does not run at all, but immediately after startup logs

```
Timestamp: 11.10.2015 20:59:24
Error: SyntaxError: missing ) after condition
Source: chrome://synckolab/content/calendarTools.js
Line: 1432, Spalte: 19
Error:
    if (!syncTasks !cur.firstChild) { 
```

and

```
Timestamp: 11.10.2015 20:59:29
Error: TypeError: synckolab.calendarTools is undefined
Source: chrome://synckolab/content/calendar.js
Line: 78
```

**Comment by corinis** [comment]
you are absolutely right... fixed that one

**Comment by adamreichold** [comment]
Indeed, the synchronization now runs through and the completion information seems to be marshalled correctly. Thank you for your help! (By the way, I think it might be useful if the nightly builds reported a version number strictly larger than the current stable version, e.g. 3.6.99.YYYYMMDDhhmm, so that Thunderbird does not "update" it to the stable version.)
